# Spring Boot Application Configuration
spring.application.name=lashback-api
server.port=8080

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (for development only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource Configuration
spring.datasource.url=ep-cool-wind-aspl33bl.c-4.eu-central-1.aws.neon.tech/neondb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xm0gCF3EWpbM
#
#spring.datasource.url=jdbc:postgresql://dpg-d7vccpt7vvec73dbn3eg-a:5432/lashes_danai
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=lashes_danai_user
#spring.datasource.password=XfIu90gJJE97Ww7bU6qR46gXz5Ta4GkN

# Logging Configuration
logging.level.root=INFO
logging.level.com.lashback=DEBUG
